package search

import (
	"fmt"
	"os"
	"path"
	"path/filepath"
	"sort"
	"strings"
)

// WriteIndexMD regenerates docs/INDEX.md deterministically from parsed
// docs. INDEX.md is a derived artifact: clobbers cost nothing because
// this function is the recovery.
func WriteIndexMD(root string, docs []Doc) error {
	byDir := map[string][]Doc{}
	for _, d := range docs {
		dir := path.Dir(strings.TrimPrefix(d.Path, "docs/"))
		if dir == "." {
			dir = "(root)"
		}
		byDir[dir] = append(byDir[dir], d)
	}
	dirs := make([]string, 0, len(byDir))
	for dir := range byDir {
		dirs = append(dirs, dir)
	}
	sort.Strings(dirs)

	var b strings.Builder
	b.WriteString("# Knowledge Index\n\nGenerated by `re-search index`. Do not edit by hand.\n")
	for _, dir := range dirs {
		b.WriteString("\n## " + dir + "\n\n")
		entries := byDir[dir]
		sort.Slice(entries, func(i, j int) bool { return entries[i].Path < entries[j].Path })
		for _, d := range entries {
			link := strings.TrimPrefix(d.Path, "docs/")
			meta := strings.TrimSuffix(strings.Join(compact(d.Status, d.Kind, d.Grade), ", "), ", ")
			line := fmt.Sprintf("- [%s](%s)", d.Title, link)
			if meta != "" {
				line += " — " + meta
			}
			if len(d.Tags) > 0 {
				line += " [" + strings.Join(d.Tags, ", ") + "]"
			}
			b.WriteString(line + "\n")
		}
	}
	return os.WriteFile(filepath.Join(root, ".re-discipline", "docs", "INDEX.md"), []byte(b.String()), 0o644)
}

func compact(vals ...string) []string {
	var out []string
	for _, v := range vals {
		if v != "" {
			out = append(out, v)
		}
	}
	return out
}
