package knowledge

import (
	"fmt"
	"strings"
)

const generatedStateSectionLimit = 50

// RenderCampaignState creates the bounded human view regenerated by every
// transaction. The JSON/Markdown records and event head remain authoritative;
// deleting this file and calling this function is always safe.
func RenderCampaignState(graph CampaignGraph) ([]byte, error) {
	if err := graph.Validate(); err != nil {
		return nil, err
	}
	var builder strings.Builder
	builder.WriteString("<!-- Generated by the re-discipline state engine. Do not edit. -->\n")
	builder.WriteString("# State: " + graph.Campaign.Title + "\n\n")
	fmt.Fprintf(&builder, "Campaign: `%s`  \nStatus: `%s`  \nRevision: `%d`  \nLast event: `%s`\n\n",
		graph.Campaign.ID, graph.Campaign.Status, graph.Campaign.Revision, graph.Campaign.LastEventID)
	builder.WriteString("## Objective\n\n" + graph.Campaign.Objective + "\n\n")
	writeStringList(&builder, "Closure criteria", graph.Campaign.ClosureCriteria)
	writeWorkSection(&builder, "Current focus", graph, graph.Campaign.CurrentFocus)

	active, blocked, deferred := []string{}, []string{}, []string{}
	for id, item := range graph.WorkItems {
		switch item.State {
		case "ready", "active":
			active = append(active, id)
		case "blocked":
			blocked = append(blocked, id)
		case "deferred":
			deferred = append(deferred, id)
		}
	}
	writeWorkSection(&builder, "Active frontier", graph, active)
	writeWorkSection(&builder, "Blocked", graph, blocked)
	writeWorkSection(&builder, "Deferred", graph, deferred)

	returned := []string{}
	for id, run := range graph.Runs {
		if run.Status == "returned" {
			returned = append(returned, id)
		}
	}
	writeRunSection(&builder, "Returned runs awaiting decision", graph, returned)
	pendingIntakes := []string{}
	for id, intake := range graph.Intakes {
		if validOne(intake.Status, "draft", "submitted") {
			pendingIntakes = append(pendingIntakes, id)
		}
	}
	writeIntakeSection(&builder, graph, pendingIntakes)
	challenged := []string{}
	for id, finding := range graph.Findings {
		if finding.Validity == "challenged" || len(finding.Relations.Contradicts) != 0 {
			challenged = append(challenged, id)
		}
	}
	writeFindingSection(&builder, graph, challenged)
	if graph.ClosureJob != nil {
		builder.WriteString("## Closure\n\n")
		fmt.Fprintf(&builder, "- Stage `%s`; status `%s`; blockers `%d`.\n\n",
			graph.ClosureJob.Stage, graph.ClosureJob.Status, len(graph.ClosureJob.Blockers))
	}
	return []byte(builder.String()), nil
}

func writeStringList(builder *strings.Builder, heading string, values []string) {
	builder.WriteString("## " + heading + "\n\n")
	if len(values) == 0 {
		builder.WriteString("- None.\n\n")
		return
	}
	for _, value := range values {
		builder.WriteString("- " + value + "\n")
	}
	builder.WriteByte('\n')
}

func boundedSorted(ids []string) ([]string, int) {
	ids = SortedUnique(ids)
	if len(ids) <= generatedStateSectionLimit {
		return ids, 0
	}
	return ids[:generatedStateSectionLimit], len(ids) - generatedStateSectionLimit
}

func writeWorkSection(builder *strings.Builder, heading string, graph CampaignGraph, ids []string) {
	builder.WriteString("## " + heading + "\n\n")
	ids, omitted := boundedSorted(ids)
	if len(ids) == 0 {
		builder.WriteString("- None.\n\n")
		return
	}
	for _, id := range ids {
		item, ok := graph.WorkItems[id]
		if !ok {
			continue
		}
		note := strings.TrimSpace(item.ResumeNote)
		if note != "" {
			note = " — " + note
		}
		fmt.Fprintf(builder, "- `%s` [%s] %s%s\n", id, item.State, item.Title, note)
	}
	if omitted > 0 {
		fmt.Fprintf(builder, "- %d additional items omitted; expand the structured graph.\n", omitted)
	}
	builder.WriteByte('\n')
}

func writeRunSection(builder *strings.Builder, heading string, graph CampaignGraph, ids []string) {
	builder.WriteString("## " + heading + "\n\n")
	ids, omitted := boundedSorted(ids)
	if len(ids) == 0 {
		builder.WriteString("- None.\n\n")
		return
	}
	for _, id := range ids {
		run := graph.Runs[id]
		fmt.Fprintf(builder, "- `%s` for `%s` by %s (%s).\n", id, run.PrimaryWorkItemID, run.ActorID, run.Role)
	}
	if omitted > 0 {
		fmt.Fprintf(builder, "- %d additional runs omitted; expand the structured graph.\n", omitted)
	}
	builder.WriteByte('\n')
}

func writeIntakeSection(builder *strings.Builder, graph CampaignGraph, ids []string) {
	builder.WriteString("## Pending intake\n\n")
	ids, omitted := boundedSorted(ids)
	if len(ids) == 0 {
		builder.WriteString("- None.\n\n")
		return
	}
	for _, id := range ids {
		intake := graph.Intakes[id]
		fmt.Fprintf(builder, "- `%s` [%s]: %d candidates, %d coverage entries.\n",
			id, intake.Status, len(intake.CandidateFindingIDs), len(intake.Coverage))
	}
	if omitted > 0 {
		fmt.Fprintf(builder, "- %d additional intake batches omitted.\n", omitted)
	}
	builder.WriteByte('\n')
}

func writeFindingSection(builder *strings.Builder, graph CampaignGraph, ids []string) {
	builder.WriteString("## Challenged or conflicted findings\n\n")
	ids, omitted := boundedSorted(ids)
	if len(ids) == 0 {
		builder.WriteString("- None.\n\n")
		return
	}
	for _, id := range ids {
		finding := graph.Findings[id]
		fmt.Fprintf(builder, "- `%s` [%s]: %s\n", id, finding.Validity, finding.Claim)
	}
	if omitted > 0 {
		fmt.Fprintf(builder, "- %d additional findings omitted.\n", omitted)
	}
	builder.WriteByte('\n')
}
